language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar --prefer-dist --dev install

script:
  - vendor/bin/phpspec run
